



//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 

    
    /**
     * Interface for: Beheerdersportaal.Api.Infrastructuur.Handlers.BaseResponse
     */
     export interface IBaseResponse {
        
        HasSucceeded: boolean;
        Error: string;
    }
 
    /**
     * Base view model for Beheerdersportaal.Api.Infrastructuur.Handlers.BaseResponse
     */
    export class BaseResponse  implements IBaseResponse  {
         
        HasSucceeded: boolean;
        Error: string;  
 
        constructor() {         
          //nothing                   
        }
    }