



//*************************DO NOT MODIFY**************************
//
//THESE FILES ARE AUTOGENERATED WITH TYPEWRITER AND ANY MODIFICATIONS MADE HERE WILL BE LOST
//PLEASE VISIT http://frhagn.github.io/Typewriter/ TO LEARN MORE ABOUT THIS VISUAL STUDIO EXTENSION
//
//*************************DO NOT MODIFY**************************
 

    
    /**
     * Interface for: Beheerdersportaal.Api.Functionaliteiten.Afdelingen.GetAfdelingenResponse
     */
     export interface IGetAfdelingenResponse extends IBaseResponse{
        
        Afdelingen: Afdeling[];
    }
 
    /**
     * Base view model for Beheerdersportaal.Api.Functionaliteiten.Afdelingen.GetAfdelingenResponse
     */
    export class GetAfdelingenResponse extends BaseResponse implements IGetAfdelingenResponse  {
         
        Afdelingen: Afdeling[];  
 
        constructor() {         
          super();                   
        }
    }